version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/api/agent"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/api/terminal"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/api/gdb"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
