upstream ela_agent_api {
    server agent-api:5000;
}

upstream ela_terminal_api {
    server terminal-api:8080;
}

server {
    listen 80;
    server_name example.com _;
    client_max_body_size 200m;

    location /terminal/ {
        proxy_pass         http://ela_terminal_api;
        proxy_http_version 1.1;
        proxy_redirect     off;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization     $http_authorization;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";

        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    location / {
        proxy_pass         http://ela_agent_api;
        proxy_http_version 1.1;
        proxy_redirect     off;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization     $http_authorization;
    }
}
